cat_name = input()
print("      /\\_/\\")
print(" /\\  / o o \\")
print("//\\\\ \\~(*)~/")
print("`  \\/   ^ /")
print("   | \\|| ||")
print("   \\ '|| ||")
print("    \\)()-())") 
print(f"My cat {cat_name}")